"""Canonical Sunni scenarios that are identical across the four schools.

Each is cross-checked against published sources - see docs/VALIDATION.md
(source keys in comments refer to entries there).
"""
import pytest

from .conftest import run

SUNNI = ["hanafi", "maliki", "shafii", "hanbali"]

# (id, heirs, expected shares)
SCENARIOS = [
    # --- spouses and children (Qur'an 4:11-12) ---
    ("husband_son", dict(husband=1, son=1),
     {"husband": "1/4", "son": "3/4"}),
    ("wife_son", dict(wife=1, son=1),
     {"wife": "1/8", "son": "7/8"}),
    ("two_wives_son", dict(wife=2, son=1),
     {"wife": "1/8", "son": "7/8"}),
    ("husband_no_desc_brother", dict(husband=1, full_brother=1),
     {"husband": "1/2", "full_brother": "1/2"}),
    ("son_only", dict(son=1), {"son": "1"}),
    ("two_sons", dict(son=2), {"son": "1"}),
    ("daughter_only_radd", dict(daughter=1), {"daughter": "1"}),
    ("two_daughters_radd", dict(daughter=2), {"daughter": "1"}),
    ("son_daughter", dict(son=1, daughter=1),
     {"son": "2/3", "daughter": "1/3"}),
    ("son_two_daughters", dict(son=1, daughter=2),
     {"son": "1/2", "daughter": "1/2"}),
    ("wife_son_daughter", dict(wife=1, son=1, daughter=1),
     {"wife": "1/8", "son": "7/12", "daughter": "7/24"}),
    # --- parents ---
    ("father_only", dict(father=1), {"father": "1"}),
    ("mother_only_radd", dict(mother=1), {"mother": "1"}),
    ("mother_father", dict(mother=1, father=1),
     {"mother": "1/3", "father": "2/3"}),
    ("umariyyatan_husband", dict(husband=1, mother=1, father=1),
     {"husband": "1/2", "mother": "1/6", "father": "1/3"}),
    ("umariyyatan_wife", dict(wife=1, mother=1, father=1),
     {"wife": "1/4", "mother": "1/4", "father": "1/2"}),
    ("father_son", dict(father=1, son=1),
     {"father": "1/6", "son": "5/6"}),
    ("father_daughter", dict(father=1, daughter=1),
     {"father": "1/2", "daughter": "1/2"}),
    ("mother_father_son", dict(mother=1, father=1, son=1),
     {"mother": "1/6", "father": "1/6", "son": "2/3"}),
    ("husband_parents_son", dict(husband=1, mother=1, father=1, son=1),
     {"husband": "1/4", "mother": "1/6", "father": "1/6", "son": "5/12"}),
    ("wife_parents_daughter", dict(wife=1, mother=1, father=1, daughter=1),
     {"wife": "1/8", "mother": "1/6", "father": "5/24", "daughter": "1/2"}),
    ("husband_mother_no_father", dict(husband=1, mother=1),
     {"husband": "1/2", "mother": "1/2"}),
    ("wife_mother", dict(wife=1, mother=1),
     {"wife": "1/4", "mother": "3/4"}),
    ("husband_father", dict(husband=1, father=1),
     {"husband": "1/2", "father": "1/2"}),
    ("wife_father", dict(wife=1, father=1),
     {"wife": "1/4", "father": "3/4"}),
    # --- awl (proportional reduction) ---
    ("awl_husband_two_sisters", dict(husband=1, full_sister=2),
     {"husband": "3/7", "full_sister": "4/7"}),
    ("awl_husband_mother_two_sisters",
     dict(husband=1, mother=1, full_sister=2),
     {"husband": "3/8", "mother": "1/8", "full_sister": "1/2"}),
    ("minbariyya", dict(wife=1, daughter=2, father=1, mother=1),
     {"wife": "1/9", "daughter": "16/27", "father": "4/27",
      "mother": "4/27"}),
    ("awl_husband_parents_daughter",
     dict(husband=1, mother=1, father=1, daughter=1),
     {"husband": "3/13", "mother": "2/13", "father": "2/13",
      "daughter": "6/13"}),
    # --- radd ---
    ("husband_one_daughter", dict(husband=1, daughter=1),
     {"husband": "1/4", "daughter": "3/4"}),
    ("husband_two_daughters", dict(husband=1, daughter=2),
     {"husband": "1/4", "daughter": "3/4"}),
    ("wife_two_daughters_mother", dict(wife=1, daughter=2, mother=1),
     {"wife": "1/8", "daughter": "7/10", "mother": "7/40"}),
    ("mother_two_uterine", dict(mother=1, maternal_brother=2),
     {"mother": "1/3", "maternal_brother": "2/3"}),
    ("husband_uterine_sister", dict(husband=1, maternal_sister=1),
     {"husband": "1/2", "maternal_sister": "1/2"}),
    ("sole_husband", dict(husband=1), {"husband": "1"}),
    ("sole_wife", dict(wife=1), {"wife": "1"}),
    # --- grandchildren ---
    ("sons_son_only", dict(sons_son=1), {"sons_son": "1"}),
    ("sons_daughter_only", dict(sons_daughter=1), {"sons_daughter": "1"}),
    ("wife_sons_son", dict(wife=1, sons_son=1),
     {"wife": "1/8", "sons_son": "7/8"}),
    ("daughter_sons_daughter", dict(daughter=1, sons_daughter=1),
     {"daughter": "3/4", "sons_daughter": "1/4"}),
    ("two_daughters_sons_daughter_blocked",
     dict(daughter=2, sons_daughter=1), {"daughter": "1"}),
    ("two_daughters_sons_son_rescues",
     dict(daughter=2, sons_daughter=1, sons_son=1),
     {"daughter": "2/3", "sons_son": "2/9", "sons_daughter": "1/9"}),
    ("daughter_sons_son_sons_daughter",
     dict(daughter=1, sons_son=1, sons_daughter=1),
     {"daughter": "1/2", "sons_son": "1/3", "sons_daughter": "1/6"}),
    ("husband_daughter_sons_daughter",
     dict(husband=1, daughter=1, sons_daughter=1),
     {"husband": "1/4", "daughter": "9/16", "sons_daughter": "3/16"}),
    # --- grandmothers ---
    ("maternal_grandmother_only", dict(maternal_grandmother=1),
     {"maternal_grandmother": "1"}),
    ("both_grandmothers", dict(maternal_grandmother=1,
                               paternal_grandmother=1),
     {"maternal_grandmother": "1/2", "paternal_grandmother": "1/2"}),
    ("mother_blocks_grandmothers",
     dict(mother=1, maternal_grandmother=1, paternal_grandmother=1),
     {"mother": "1"}),
    ("son_grandmothers", dict(son=1, maternal_grandmother=1,
                              paternal_grandmother=1),
     {"son": "5/6", "maternal_grandmother": "1/12",
      "paternal_grandmother": "1/12"}),
    # --- siblings ---
    ("husband_full_sister", dict(husband=1, full_sister=1),
     {"husband": "1/2", "full_sister": "1/2"}),
    ("full_brother_full_sister", dict(full_brother=1, full_sister=1),
     {"full_brother": "2/3", "full_sister": "1/3"}),
    ("full_brother_blocks_paternal",
     dict(full_brother=1, paternal_brother=1, paternal_sister=1),
     {"full_brother": "1"}),
    ("full_sister_paternal_sister",
     dict(full_sister=1, paternal_sister=1),
     {"full_sister": "3/4", "paternal_sister": "1/4"}),
    ("two_full_sisters_block_paternal_sister",
     dict(full_sister=2, paternal_sister=1), {"full_sister": "1"}),
    ("two_full_sisters_paternal_brother_rescues",
     dict(full_sister=2, paternal_sister=1, paternal_brother=1),
     {"full_sister": "2/3", "paternal_brother": "2/9",
      "paternal_sister": "1/9"}),
    ("uterine_brother_only", dict(maternal_brother=1),
     {"maternal_brother": "1"}),
    ("uterine_pair_equal_split",
     dict(maternal_brother=1, maternal_sister=1, full_brother=1),
     {"maternal_brother": "1/6", "maternal_sister": "1/6",
      "full_brother": "2/3"}),
    ("father_blocks_siblings_mother_sixth",
     dict(mother=1, father=1, full_brother=2),
     {"mother": "1/6", "father": "5/6"}),
    ("son_blocks_siblings", dict(son=1, full_brother=1, maternal_sister=1,
                                 paternal_brother=1),
     {"son": "1"}),
    ("daughter_does_not_block_full_brother",
     dict(wife=1, daughter=1, full_brother=1),
     {"wife": "1/8", "daughter": "1/2", "full_brother": "3/8"}),
    # --- sisters with daughters (ma'a al-ghayr) ---
    ("daughter_full_sister_residuary", dict(daughter=1, full_sister=1),
     {"daughter": "1/2", "full_sister": "1/2"}),
    ("two_daughters_full_sister", dict(daughter=2, full_sister=1),
     {"daughter": "2/3", "full_sister": "1/3"}),
    ("daughter_full_sister_blocks_paternal_brother",
     dict(daughter=1, full_sister=1, paternal_brother=1),
     {"daughter": "1/2", "full_sister": "1/2"}),
    ("daughter_paternal_sister_residuary",
     dict(daughter=1, paternal_sister=1),
     {"daughter": "1/2", "paternal_sister": "1/2"}),
    # --- distant agnates ---
    ("full_nephew_only", dict(full_brothers_son=1),
     {"full_brothers_son": "1"}),
    ("full_nephew_blocks_paternal_nephew",
     dict(full_brothers_son=1, paternal_brothers_son=1),
     {"full_brothers_son": "1"}),
    ("full_uncle_blocks_paternal_uncle",
     dict(full_paternal_uncle=1, paternal_paternal_uncle=1),
     {"full_paternal_uncle": "1"}),
    ("uncle_chain_cousins", dict(full_uncles_son=1, paternal_uncles_son=1),
     {"full_uncles_son": "1"}),
    ("wife_full_uncle", dict(wife=1, full_paternal_uncle=1),
     {"wife": "1/4", "full_paternal_uncle": "3/4"}),
    ("brother_blocks_nephew", dict(full_brother=1, full_brothers_son=1),
     {"full_brother": "1"}),
]


@pytest.mark.parametrize("madhhab", SUNNI)
@pytest.mark.parametrize("name,heirs,expected",
                         SCENARIOS, ids=[s[0] for s in SCENARIOS])
def test_sunni_scenario(madhhab, name, heirs, expected):
    run(madhhab, expected, **heirs)
